Wip/dsp 1076 cleanup api logging
dasch-swiss/dsp-tools pull request #46
Opened 2021-02-08 21:52 UTC by lrosenth

Some cleanup of lgging of API errors
Some small fixes for the rosetta project

Afterwards acceptance a new version for Pypi will be created...

2021-02-09 08:14 UTC, subotic requested changes
There are two CI errors that need to be fixed first. You can run the same tests locally with running `make test`.

2021-02-10 00:18 UTC, lrosenth commented
OK, test run through. rosetta is supported.... Let's fetz -- eh -- merge

2021-02-10 08:57 UTC, subotic approved these changes

2021-02-10 08:57 UTC, merged

2021-02-10 08:58 UTC, subotic commented
@lrosenth thanks, I've merged it.